[data_sources]

[data_sources.ClickHouseDB]
type = "ClickHouse"
[data_sources.ClickHouseDB.conn_props.Main]
hostname = "hyperdx-hdx-oss-v2-clickhouse.dev"
port = 9000

[data_sources.NATS]
type = "NATS"
[data_sources.NATS.conn_props.Main]
hostname = "nats.dev"
port = 4222

[data_sources.Kafka]
type = "Kafka"
[data_sources.Kafka.conn_props.Main]
hostname = "kafka-cluster-kafka-brokers.dev"
port = 9092