apiVersion: apps/v1
kind: Deployment
metadata:
  name: refdata-cmd-executor
  labels:
    app: refdata-cmd-executor
spec:
  replicas: 4
  selector:
    matchLabels:
      app: refdata-cmd-executor
  template:
    metadata:
      labels:
        app: refdata-cmd-executor
    spec:
      imagePullSecrets:
        - name: arq-dockerhub-cred
      containers:
        - name: refdata-cmd-executor
          # This matches the image your CI pipeline just built
          image: ej20002011/arq:master
          imagePullPolicy: Always
          command: ["RefDataCmdExecutor"]

          ports:
            - name: admin-port
              containerPort: 8080

          startupProbe:
            httpGet:
              path: /health/startup
              port: admin-port
            failureThreshold: 100 # 100 * 3 = 300 seconds = 5 minutes to give for startup
            periodSeconds: 3

          readinessProbe:
            httpGet:
              path: /health/ready
              port: admin-port
            failureThreshold: 3
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health/live
              port: admin-port
            failureThreshold: 3
            periodSeconds: 5

          resources:
            limits:
              memory: "2G"
              cpu: "2"
            requests:
              memory: "512M"
              cpu: "500m"
