apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - services

configMapGenerator:
  - name: arq-dev-env-vars
    literals:
      - ARQ_log_level=DEBUG

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: arq-dev-env-vars